[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm i -g pnpm && pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'pnpm prisma:deploy && node dist/index.js'
